logsBucket: gs://my-test-bucket-00
steps:

  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']
    dir: '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/studied-yen-423602-b9/gcloud-build-testimg:tag', '.']
    dir: '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/studied-yen-423602-b9/gcloud-build-testimg:tag']

serviceAccount: your-service-account@studied-yen-423602-b9.iam.gserviceaccount.com
