logsBucket: gs://test_bucket_build
steps:

  - name: 'batrick-swaistan/cloud-builders/mvn'
    args: ['clean', 'package']
    dir: '.'
  - name: 'batrick-swaistan/cloud-builders/docker'
    args: ['build', '-t', 'batrick-swaistan/sandbox-427408/gcloud-build-testimg:tag', '.']
    dir: '.'
  - name: 'batrick-swaistan/cloud-builders/docker'
    args: ['push', 'batrick-swaistan/sandbox-427408/gcloud-build-testimg:tag']

serviceAccount: sandbox-427408@appspot.gserviceaccount.com
